name: Update README.md
on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - run: npm install
    - run: npm run generate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update README.md (bot)
        commit_user_name: Github Action
